### ISSUE TITLE
re-experimentation-performance

### ISSUE THREAD

**Issue by daydayupzzl** [595693085/DGraphDTA#11]

**Comment by 595693085** [comment]
Hi,
if you could not run on the Davis dataset, please check if all data files exist, and if you do not want to genereate the preprocess files, you can download form the provided link.

**Comment by daydayupzzl** [comment]
Thank you very much for your reply. At first, I directly used the trained model in the warehouse to reproduce the effect of the paper, but I found that the reproduction gap was a little big, so I published this issue. Fortunately, I found that maybe I need to retrain DGraphDTA to reproduce the effect in the paper. May I ask whether the effect of running DGraphDTA model on my device will be the same as that in the paper? I am looking forward to your answer. Thank you for your attention!

**Comment by 595693085** [comment]
Hi,
Thanks for the attention of our work, just run the test.py script in the repository for the prediction, then the same performance of the experimence will be reproduced.

**Comment by 595693085** [comment]
Furthermore, the code here only includes experiments for parameter fitting, while other experimental settings are described in detail in the manuscript and the model need to be trained and tested according to the description in the manuscript.

**Comment by daydayupzzl** [comment]
i have got it ！thanks a lot！😄
