### ISSUE TITLE
uniclust30_2018_08

### ISSUE THREAD

**Issue by mahmodDAHOL** [595693085/DGraphDTA#12]
when i download uniclust30_2018_08 dataset, the folder has 4 files as follow:
1- uniclust30_2018_08.tsv
2- uniclust30_2018_08_consensus.fasta
3- uniclust30_2018_08_md5sum
4- uniclust30_2018_08_seed.fasta
so which on i have to use in scripts.py file?

**Comment by 595693085** [comment]
Hi,
The dataset processing in the script refers to HHblits, so you can find detailed processes for msa on their website https://github.com/soedinglab/hh-suite. The processed dataset file path should be a folder. Hope it works.
