### ISSUE TITLE
Properties of selenocysteine

### ISSUE THREAD

**Issue by wanglong0228** [595693085/DGraphDTA#13]
Hello, I encountered selenocysteine when processing the data set. Can the attribute of this amino acid be provided, or I want to know where to get the attribute of this amino acid.

**Comment by 595693085** [comment]
Hi,
thanks for the attention on our work, this amino acid may be not a common amino acid, so we replace it with "X", means a unkonwn amino acid. And its attribute was not provided in the literatures.
