### ISSUE TITLE
Code run error

### ISSUE THREAD

**Issue by Xiaolin-Yang-S** [595693085/DGraphDTA#14]
![FX4P~QE89N%@63AU9`S9@9](https://github.com/595693085/DGraphDTA/assets/62194533/5b913100-f2dd-4c50-aaa9-4633bbcfea44)

When I run this code, I encounter an error like the one above. By looking for a solution to the problem online, I suspect it is because the tensor is too large, but I have no good solution. I hope you can help me answer this question, thank you.

**Comment by 595693085** [comment]
Thanks fo the attention on our work, you can try to redue the batch size, hope it works!
