### ISSUE TITLE
Error on pconsc4

### ISSUE THREAD

**Issue by WGDMS** [595693085/DGraphDTA#17]
import pconsc4
    import keras.backend.tensorflow_backend as KTF

Please let me know how to correctly install these two?

I tried '!pip install pconsc4'.

But error was: Downloading pyGaussDCA-1.0.tar.gz (3.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 70.2 MB/s eta 0:00:00
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by 595693085** [comment]
Sorry for the failure of installation for pconsc4. The toolkit is not development by us, so you can refer to the Pcons4 for help.
