### ISSUE TITLE
About contact map data files

### ISSUE THREAD

**Issue by hyojin0912** [595693085/DGraphDTA#18]
Thank you very much for creating a good model and sharing your data. 
I would like to train the model on proteins other than the ones you used, and I was wondering if you have any contact map data files for other proteins. (Not Kinase, such as GPCR)
If I need to create one, I think the running of the alnFilePrepare function needs proteins.txt as input.
How do I create a proteins.txt for the proteins I want to experiment with?

**Comment by 595693085** [comment]
Thanks for you attention on our work. Actually, we provided a script for contact map generation in the code, but it took a long time for it with Pcons4 toolkit. Now, the ems2 model provide a faster and accurate way (a few seconds) for contact map generation on a sequence, and it is easy to implement it (code with three lines). So esm2 (opensouce on github) may solve your problem.
