### ISSUE TITLE
loading trained model error

### ISSUE THREAD

**Issue by mtnrzna** [595693085/DGraphDTA#19]
Hello,
I hope this message finds you well. I'm writing to report an issue I encountered while trying to run the test.py script with a trained model. Also I downloaded the dataset from the mentioned google drive link and executed the test.py script with the command:
`python test.py 0 0` and also `python test.py 1 0` (for davis and kiba respectedly)
Both of these, raised the same error which indicate indicates missing and unexpected keys in the model's state dictionary. The error:

_Traceback (most recent call last):
  File "/content/DGraphDTA/test.py", line 107, in <module>
    model.load_state_dict(torch.load(model_file_name, map_location=cuda_name))
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GNNNet:
    Missing key(s) in state_dict: "mol_conv1.lin.weight", "mol_conv2.lin.weight", "mol_conv3.lin.weight", "pro_conv1.lin.weight", "pro_conv2.lin.weight", "pro_conv3.lin.weight".
    Unexpected key(s) in state_dict: "mol_conv1.weight", "mol_conv2.weight", "mol_conv3.weight", "pro_conv1.weight", "pro_conv2.weight", "pro_conv3.weight"._

---------
Plus I trained the model on only one fold, using `python train.py 0 0 0` command, and I use the exact same code from this repo(lr and epochs and all the same and unchanged) and I got about **0.22993203** for the best validset mse for fold 0 of davis and **0.23218115** for testset of davis, which are far worse than the articles results, any idea on this matter? maybe a hint on what did I do wrong here?any ideas why this happens?
![image](https://github.com/595693085/DGraphDTA/assets/58879716/9da183e5-fe3c-4ce9-8d06-5175bd5a6637)

I appreciate your time and assistance in resolving this matter. Thank you.

**Comment by 595693085** [comment]
Thanks for your attention on our work, the 5-fold result took the average results of the 5 folds, so you should run the whole folds. Also, for each hold,  the results are different, so you if run the experiences several times, you may get different results. The setting of the performance experiment is the same as GraphDTA and is mentioned in the article, and you may get even better result than the article if you run several times.

**Comment by mtnrzna** [comment]
Aha. I got it. Thanks a lot.
