### ISSUE TITLE
How to compare the performances using the actual contact map and Pconsc4-predicted contact map?

### ISSUE THREAD

**Issue by xueeinstein** [595693085/DGraphDTA#3]
![image](https://user-images.githubusercontent.com/3424201/106088145-56720600-6160-11eb-9b0b-3ee26953ee20.png)
I found your paper mentioned this experiment. However, as I know, many proteins in Davis and Kiba do not have experimental PDB data of the full sequences. How do you get the actual contact map since no ground truth PDB available?

**Comment by 595693085** [comment]
Hi, sorry for the late reply. For KIBA dataset, we can get the uniprot entry from its uniprot id, which is named in the dataset, then we can get the  actual structure from its uniprot id. By the way, beacuse the real structure may loss some residue, so we should cut off the predicted contact map to keep them consistent.
