### ISSUE TITLE
How to prepare new data for predition?

### ISSUE THREAD

**Issue by xuzhang5788** [595693085/DGraphDTA#4]
What is your input data format? If I have a pair of protein and compound. I want to know the affinity of this pair. What information and format do you need to do this prediction with your trained model？Thanks

**Comment by 595693085** [comment]
Hi, for a new protein-drug pair, we just need the smiles for drug and .a3m file for protein (generated by HHblits), and the .a3m file is used for contact map prediction (refer to Pconsc4 project), then you can follow our code to construct protein and drug graph for the affinity prediction.
