### ISSUE TITLE
protein id P78527

### ISSUE THREAD

**Issue by tanthanh0510** [595693085/DGraphDTA#5]
Hi mr.Jiang, during the re-experimentation, when loading the processed data, the .npy file of protein id P78527 in the folder pconsc4 dataset kiba was lost. Can you give me the full processed data? thank you!

**Comment by 595693085** [comment]
Hi, acctually we have mentioned in the manuscript that one protein is too big for contact map prediciton with Pconsc4 in our server. So if you want to involve the protein, you can predict its contact map with a big RAM server or cut off the sequence with a short length (such as 1000). The prediction process can refer to Pconsc4 project, which uses .a3m file for predicition. Then a full dataset can be obtained.
