### ISSUE TITLE
How to adjust parameters for HHblitsMSA() in script.py

### ISSUE THREAD

**Issue by qwe1997** [595693085/DGraphDTA#6]
Hi, I am going to using my own protein data to get protein representation,however when I am running script.py,I find it takes too much time for HHbits command in HHblitsMSA(),So I consulted the developer for HH-suite,He told me  'time depend also on how many iterations you run'.So I want to know ?
1.How do you get the appropriate parameters for HHbits command in HHblitsMSA() of script.py?
2.How do I adjust the parameters for iterations or other pameters to  accelerate the program?

**Comment by 595693085** [comment]
Thanks for your attention. There are some suggestions which may help you to solve your problem.
For your first question, the HHBits parameters are given in the  HHblitsMSA() function (line 33). You can run it in a linux shell to generate the MSA profile. For your second question, the HHblitsMSA() is implemeted with a check proceduce (line 25), so if a protein sequence is given, the code will check if there are MSA files for it first, then the code will run for the protein without MSA files. Thus, if you want to accelerate the program, just open several terminals to run the scripts at the same time. For instance, If you have a cpu with 8 cores, just open 8 terminals to run the same script.
