### ISSUE TITLE
Unable to download the preprocessed "data.zip"

### ISSUE THREAD

**Issue by HinamonAmu** [595693085/DGraphDTA#7]
Hello, 
      I want to skip the lengthy data preprocessing steps, but when I click the link to download the "**data.zip**" file, the webpage frequently terminates my download process and finally displays "Failed-has been banned". 
      Do you have any good solutions? Thanks and best regards！

**Comment by 595693085** [comment]
Hi,
       Thanks for the attention about our work! The data has been uploaded to the google cloud, which is out of our control. I suggest you change your network to try it again, or use VPN to download the data. Hope it works!
