### ISSUE TITLE
OSError 

### ISSUE THREAD

**Issue by XueWang2019** [595693085/DGraphDTA#8]
Hello,
I try to skip the data preprocessing process: download the dataset, put them in the folder, install rdkit, torch, and all are fine. I run it on google colab with GPU. When run "!python training_5folds.py 0 0 0", then there is error:
OSError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

I searched, and find somebody mentioned that: need to set LD_LIBRARY_PATH for Cuda.  Or maybe downgrade Cuda to Cuda 10, as the current Cuda 11 is used, but that will cause all of the settings redos. 

Before redoing everything, may I ask whether it is the reason? Does it is needed to be set to run the trained model?
Thanks.

**Comment by kiki-win** [comment]
> 你好， 我尝试跳过数据预处理过程：下载数据集，放入文件夹，安装rdkit，torch，一切正常。我在带有 GPU 的 google colab 上运行它。运行“！python training_5folds.py 0 0 0”时，出现错误： OSError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
> 
> 我搜索了一下，发现有人提到：需要为 Cuda 设置 LD_LIBRARY_PATH。或者可能将 Cuda 降级到 Cuda 10，因为使用的是当前的 Cuda 11，但这会导致所有设置重做。
> 
> 在重做之前，请问是不是这个原因？是否需要设置才能运行经过训练的模型？ 谢谢。
你好，请问是否可以分享下经过预处理的数据，我这里无法下载，谢谢。

**Comment by 595693085** [comment]
This may be the the envieonment error, which is not related to the code. So you should install the the cuda and pytorch carefully. The processed data is very large, which is not easy to transmit it. We uploaded it on google cloud. If you could not open it, try to use a vpn proxy.

**Comment by 595693085** [comment]
> > 你好， 我尝试跳过数据预处理过程：下载数据集，放入文件夹，安装rdkit，torch，一切正常。我在带有 GPU 的 google colab 上运行它。运行“！python training_5folds.py 0 0 0”时，出现错误： OSError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
> > 我搜索了一下，发现有人提到：需要为 Cuda 设置 LD_LIBRARY_PATH。或者可能将 Cuda 降级到 Cuda 10，因为使用的是当前的 Cuda 11，但这会导致所有设置重做。
> > 在重做之前，请问是不是这个原因？是否需要设置才能运行经过训练的模型？ 谢谢。
> > 你好，请问是否可以分享下经过预处理的数据，我这里无法下载，谢谢。

应该与代码无关，单纯的环境问题，重新装装试试吧。预处理的数据说实话太大了，只能传到谷歌云了，用VPN试试吧。
