### ISSUE TITLE
how to install hhsuite and ccmpred?? And What system are you running this program on？

### ISSUE THREAD

**Issue by pipijiev12** [595693085/DGraphDTA#9]
1.how to install hhsuite and ccmpred??
2. And What system are you running this program on？
3. Currently the problem I'm having is:Exception: “Program HHblits was not found. Please specify the run path.”
4. I have installed HHblits and can run the command HHblits, but the program reports this error

**Comment by 595693085** [comment]
Hi, here are some suggestions that may help you to solve the problems.
1. The installation could be refer to their official page.
2. The system we used is Ubuntu 18.04
3. After you install all the programs, please change the code in "scripts.py" in line 120-124 to your own programs path, which are :
        HHblits_bin_path = '..../tool/hhsuite/bin/hhblits'  # HHblits bin path
        HHblits_db_path = '..../dataset/uniclust/uniclust30_2018_08/uniclust30_2018_08'  # hhblits dataset for msa
        HHfilter_bin_path = '..../tool/hhsuite/bin/hhfilter'  # HHfilter bin path
        reformat_bin_path = '..../tool/hhsuite/scripts/reformat.pl'  # reformat bin path
        convertAlignment_bin_path = '..../tool/CCMpred/scripts/convert_alignment.py'  # ccmpred convertAlignment bin path
4. Please change the script code in line 120-124 to your own path which are explained in detail above.  
Hope it works!

**Comment by mahmodDAHOL** [comment]
can i download them on windows 10?
if so, how?

**Comment by 595693085** [comment]
> 

Hi,
We run the program on Ubuntu 18.04, we have not tested it on Windows.  Acutally, the running of the program mainly depends on whether the imported toolkits could be run through, such as HHblits, CCMpred and Pcons4. These toolkits are beyond our control and you should refer to their official page.  So if you run through the toolkits and Pytorch, then the scripts could be easy to run through. Hope it can help you.

**Comment by mahmodDAHOL** [comment]
Thank you very much

في الجمعة، ٢ ديسمبر ٢٠٢٢ ١١:٤٣ ص Jiang Mj ***@***.***> كتب:
